
model: "models/llama-2-7b-chat.gguf"

ctx_size: 4096
predict: 512
batch_size: 512

threads: 8

temperature: 0.7
top_k: 40
top_p: 0.9
repeat_penalty: 1.1
seed: -1

conversation: true
system_prompt: "You are a helpful, harmless, and honest AI assistant."

interactive: true

antiprompt:
  - "User:"
  - "Human:"
